version: '3.7'

services: 

  dvc-calc-ui:
    image: tbichse/dvc-calc-ui:1.1
    stdin_open: true
    ports: 
      - 4000:3000
    depends_on:
      - dvc-calc-api
  
  dvc-calc-api:
    image: tbichse/dvc-calc-api:1.1
    stdin_open: true
    environment:
      NODE_ENV: dev
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    ports: 
        - 4001:3001
    depends_on:
      - db
  
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql