version: '3.7'

services: 

  dvc-calc-ui:
    image: tbichse/dvc-calc-ui:1.5-ubuntu
    container_name: dvc-calc-ui 
    stdin_open: true
    ports: 
      - 8080:80
    depends_on:
      - dvc-calc-api
  
  dvc-calc-api:
    image: tbichse/dvc-calc-api:1.2-ubuntu
    container_name: dvc-calc-api
    stdin_open: true
    environment:
      NODE_ENV: dev
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    ports: 
        - 3001:3001
    depends_on:
      - db
  
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'nginxproxymanager'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"

    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt

networks:
  default:
    external:
      name: nginxproxy

